app:
 env: dev
 http_addr: ":8080"

mysql:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "#ES147258369#"
  database: "quick_im"
  charset: "utf8mb4"

redis:
  host: "127.0.0.1"
  port: 6379
  username: "root"
  password: "88888888"
  channel: "quick_im"

jwt:
  secret: "quick_im_secret"
  expire_hours: 2