app:
  env: dev
  http_addr: ":8000"

mysql:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "change-me"
  database: "quick_im"
  charset: "utf8mb4"

redis:
  host: "127.0.0.1"
  port: 6379
  username: ""
  password: ""
  channel: "quick_im"

jwt:
  secret: "replace-with-a-random-secret"
  expire_hours: 2
